version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: perf-postgresql
    command: -c 'max_connections=1000'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: perf_db
